-- Migration number: 0002 generated by teenybase on 2026-06-04T10:17:53.576Z. Do not modify this file.

CREATE TABLE kv_store (
	key TEXT PRIMARY KEY NOT NULL, 
	value JSON NOT NULL, 
	expire TIMESTAMP
);