-- Migration number: 0003 generated by teenybase on 2026-06-04T10:17:53.576Z. Do not modify this file.

CREATE TABLE giveaways (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	guild_id TEXT NOT NULL, 
	prize TEXT NOT NULL, 
	description TEXT DEFAULT "", 
	channel_id TEXT NOT NULL, 
	channel_name TEXT NOT NULL, 
	winner_count INTEGER NOT NULL DEFAULT 1, 
	start_at TIMESTAMP, 
	ends_at TIMESTAMP NOT NULL, 
	status TEXT NOT NULL DEFAULT "active", 
	participants INTEGER NOT NULL DEFAULT 0, 
	winners JSON DEFAULT "[]", 
	required_role_ids JSON DEFAULT "[]", 
	required_role_names JSON DEFAULT "[]", 
	bonus_roles JSON DEFAULT "[]", 
	created_by TEXT NOT NULL
);
CREATE INDEX idx_giveaways_guild_id ON giveaways (guild_id);
CREATE INDEX idx_giveaways_status ON giveaways (status COLLATE NOCASE);
CREATE INDEX idx_giveaways_ends_at ON giveaways (ends_at);
CREATE TRIGGER tgr_giveaways_raise_on_created_update BEFORE UPDATE OF created ON giveaways BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;